AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local simulation of Lambda + API Gateway

Resources:
  ApiLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda/handler.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 10
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
