name: Deploy CDK App

on:
  push:
    branches:
      - main   # deploy to PROD
      - dev    # deploy to DEV

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # required for OIDC federation
      contents: read    # required for checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::412381746256:role/githubAccessECRECSRole
          aws-region: ap-southeast-1   # adjust if needed

      - name: Install dependencies
        run: npm install

      - name: Bootstrap CDK (first-time only)
        run: npx cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_REGION
        env:
          AWS_REGION: ap-southeast-1
          AWS_ACCOUNT_ID: 412381746256

      - name: Synthesize CloudFormation
        run: npx cdk synth

      - name: Deploy to AWS
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            npx cdk deploy --require-approval never --all -c stage=prod
          else
            npx cdk deploy --require-approval never --all -c stage=dev
          fi
