name: Deploy Canary API (CDK)

on:
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::412381746256:role/githubAccessECRECSRole
          aws-region: ap-southeast-2

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: CDK Bootstrap (idempotent)
        run: npx cdk bootstrap aws://412381746256/ap-southeast-2

      - name: Deploy (canary auto-promotion via CodeDeploy)
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "Deploying PROD..."
            npx cdk deploy ApiStack-prod --require-approval never -c stage=prod
          else
            echo "Deploying DEV..."
            npx cdk deploy ApiStack-dev --require-approval never -c stage=dev
          fi
